### ISSUE TITLE
Test that posts created after a connection is created, are not included in the new connection's feed

### ISSUE THREAD

**Issue by kerkeslager** [kerkeslager/friendzone#19]
A user should be able to add a new connection, without worrying that adding that connection will allow the person to see some past post which contains content shared without that person in mind.

To this end, new connections shouldn't be able to see the connecting users' old posts in their feed.

Let's write a test to ensure that this is, and always will be, how posts work.

I think this already works because of the way posts are currently connected to users, but if it doesn't, let's fix it as part of this issue.

**Comment by nkzarrabi** [comment]
#82 

Having some issues , @kerkeslager . 
This may also impact #82
