### ISSUE TITLE
Integration Test Post Process

### ISSUE THREAD

**Issue by kerkeslager** [kerkeslager/friendzone#51]
The post process seems mature enough that we can test this path:

1. Create three users (0, 1, 2) in the database. Make users 0 and 1 Friends, and users 0 and 2 Family. Don't need to do this through frontend because that's already tested, but from here on out use the frontend.
2. Log in as user 0 and publish a post to their Friends.
3. Verify that user 0 can view the post.
4. Log in as user 1 and verify that user 1 can view the post.
5. Log in as user 2 and verify that user 2 CANNOT view the post.

**Comment by nkzarrabi** [comment]
Sorry, didn't mean to create a pull request for that. Don't want to merge with main yet.
https://github.com/kerkeslager/friendzone/tree/51-integration-test-post-process

Having issues , @kerkeslager . 
This could also impact potentially, as I'm only checking if posts cannot be seen (this would be the case if no post shows at all, regardless of when it is made. 
#82

**Comment by kerkeslager** [comment]
I commented on the PR. That test seems to be passing?
