### ISSUE TITLE
feed not showing connection's new post 

### ISSUE THREAD

**Issue by nkzarrabi** [kerkeslager/friendzone#97]
#51 
In 51, we discovered  a broken feed during integration testing.
The suspicion is that the post is not creating publication links in other users feeds, like it does in unit tests.
Going to be revising this

**Comment by nkzarrabi** [comment]
https://github.com/kerkeslager/friendzone/pull/83
Having issues with 
  File "/home/runner/work/friendzone/friendzone/core/test_models.py", line 480, in test_feed_does_not_contain_old_posts_for_new_connection
    self.assertNotIn(post, reading_user.feed.all())
AssertionError: <Post: Post object (f9931cb2-4233-441f-854e-5cb935013981)> unexpectedly found in <QuerySet [<Post: Post object (f9931cb2-4233-441f-854e-5cb935013981)>]>

After changing feed(self)

**Comment by kerkeslager** [comment]
This was fixed in a PR which is now merged to main
